### ISSUE TITLE
Moto E not supported?

### ISSUE THREAD

**Issue by gciccarelli3** [ohmage/android#95]
Hi,

Can you provide any information as to why the Moto E android phone would be declared incompatible with Ohmage?  It's android version 4.4.4.  I have no data plan/ carrier associated with the phone.  Is that required?

Thank You,
Greg

**Comment by gr21783** [comment]
Hi Steve,

Happy New Year!  We've solved our enrollment issue but have hit another
stumbling block.  We tried to relocate the mysql database to a mounted
volume on the amazon ec2 instance.  Everything seemed to go fine until I
had to restart the mysql server.  I'm not sure if this error is independent
of the ohmage installation or not.  Also, is there any way to install the
ohmage mysql database directory directly on the external drive rather than
trying to move it?

I followed this procedure here, until the end where I tried all
permutations that I could think of for restarting the server and editing
files based on the comments.
http://stackoverflow.com/questions/1795176/how-to-change-mysql-data-directory

I was able to relocate the audio and video directories, but I need to move
all the table information to the encrypted drive, hence this more involved
process.

Thanks,
Greg

**Comment by gr21783** [comment]
$ service mysql restart
stop: Unknown instance:
start: Rejected send message, 1 matched rules; type="method_call",
sender=":1.26" (uid=1000 pid=29233 comm="start mysql ")
interface="com.ubuntu.Upstart0_6.Job" member="Start" error name="(unset)"
requested_reply="0" destination="com.ubuntu.Upstart" (uid=0 pid=1
comm="/sbin/init")

**Comment by gr21783** [comment]
Never mind-  I think I got it- or at least that error.  Knock on wood.

**Comment by stevenolen** [comment]
Hi Greg!

Glad to see you're making progress! The movement of mysql is really more of a system-level issue, but I'm happy to give you a bit more insight into ohmage's use of the db (and a typical way to migrate the ohmage data to another system. 

Firstly, ohmage connects to the database only through the connection specified in /etc/ohmage.conf (or the default property set which is located [here](https://github.com/ohmage/server/blob/master/web/WEB-INF/config/default.properties). you can modify the port/address to point the container to another mysql instance.  Once you have a connection to the new database, you can either dump and restore the ohmage data (via `mysql -uohmage -p ohmage > /old/system/ohmage_db_dump.sql` and then `mysql -uohmage -p ohmage < /new/system/ohmage_db_dump.sql`) or if you don't have any data that needs to be restored, you can just prep the database as new. Prepping the database as new can be done by executing a number of these sql scripts from this directory: https://github.com/ohmage/server/tree/master/db/sql

You'll need:
  * `base/ohmage-ddl.sql`
  * `preferences/default-preferences.sql`
  * all files from settings

If you do the prep method, you'll probably need to set a few parameters in the preferences table (such as where your static content directories are located etc.).  When you start ohmage, check out `/var/log/ohmage/ohmage.log` (or wherever you've specified your log directory to be), it'll let you know if you've missed something!

Good luck!

**Comment by stevenolen** [comment]
one more thing to note here, I see you mention an encrypted disk for the db data.  Since you're using ec2, you may want to look in to using amazon rds (http://aws.amazon.com/rds/) for your db connection to ohmage, since it provides data-at-rest encryption and removes your need to manage an encrypted disk.
